[[plugins]]
repo = 'Shougo/dein.vim'

# ==========================================================
# color
# ==========================================================

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
set background=dark
au MyAutoCmd VimEnter * nested colorscheme hybrid
au MyAutoCmd VimEnter * highlight Visual ctermbg=216
'''

# ==========================================================
# linter
# ==========================================================

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
source ~/dotfiles-re/nvim/plugins/ale.rc.vim
'''
