# ==========================================================
# filer
# ==========================================================


# ==========================================================
# Denite
# ==========================================================

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
source ~/dotfiles-re/nvim/plugins/denite.rc.vim
'''
hook_post_source = '''
" call denite#custom#var('grep', 'command',
" \ ['pt', '--nogroup', '--nocolor', '--smart-case', '--hidden'])
" call denite#custom#var('grep', 'default_opts', [])
" call denite#custom#var('grep', 'recursive_opts', [])
" denite/insert モードのときは，C- で移動できるようにする
call denite#custom#map('insert', "<C-j>", '<denite:move_to_next_line>')
call denite#custom#map('insert', "<C-k>", '<denite:move_to_previous_line>')
" tabopen や vsplit のキーバインドを割り当て
call denite#custom#map('insert', "<C-t>", '<denite:do_action:tabopen>')
call denite#custom#map('insert', "<C-v>", '<denite:do_action:vsplit>')
call denite#custom#map('normal', "v", '<denite:do_action:vsplit>')
call denite#custom#source('file_rec', 'matchers', ['matcher_fuzzy','matcher_ignore_globs'])
call denite#custom#filter('matcher_ignore_globs', 'ignore_globs',
      \ [
      \ '.git/', 'node_modules/*', 'build/', '__pycache__/',
      \ 'images/', '*.o', '*.make',
      \ '*.min.*',
      \ 'img/', 'fonts/'])
'''

[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['Shougo/denite.nvim']

# ==========================================================
# Deoplete
# ==========================================================

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_add = '''
source ~/dotfiles-re/nvim/plugins/deoplete.rc.vim
'''

# Snippet
[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = 'let g:neosnippet#enable_completed_snippet = 1'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# JavaScript
[[plugins]]
repo = 'wokalski/autocomplete-flow'
on_source = ['Shougo/deoplete.nvim']

# Ruby
[[plugins]]
repo = 'Shougo/deoplete-rct'
on_ft = ['ruby']
on_source = ['Shougo/deoplete.nvim']

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = ['ruby']
on_source = ['Shougo/deoplete.nvim']

# ==========================================================
# terminal
# ==========================================================

# [[plugins]]
# repo = 'kassio/neoterm'
# if = "has('nvim')"
# hook_add = '''
# source ~/dotfiles-re/nvim/plugins/neoterm.rc.vim
# '''

[[plugins]]
repo = 'Shougo/vimshell'
if = "!has('nvim')"
hook_add = '''
source ~/dotfiles-re/nvim/plugins/vimshell.rc.vim
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
if = "!has('nvim')"
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

# ==========================================================
# Yank
# ==========================================================

[[plugins]]
repo     = 'LeafCage/yankround.vim'
on_map   = ['<Plug>(yankround-']
hook_add = '''"{{{
  nmap p <Plug>(yankround-p)
  xmap p <Plug>(yankround-p)
  nmap P <Plug>(yankround-P)
  nmap gp <Plug>(yankround-gp)
  xmap gp <Plug>(yankround-gp)
  nmap gP <Plug>(yankround-gP)
  nmap <c-p> <Plug>(yankround-prev)
  nmap <expr><c-n> yankround#is_active() ? "\<Plug>(yankround-next)" : "\<Plug>DWMNew"
"}}}'''


# コメントアウト、アンコメントを楽にする
[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'scrooloose/nerdtree'

# ==========================================================
# Highlight, Colorschema
# ==========================================================
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript']

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html', 'vue']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'php', 'erb', 'scss', 'sass', 'css', 'jade', 'haml', 'pug', 'less', 'vue']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'md'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'digitaltoad/vim-jade'
on_ft = 'jade'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

# ステータスラインを良い感じにする
# deniteとキーバインドが被る?ので一旦外す
# [[plugins]]
# repo = 'itchyny/lightline.vim'
# hook_add = '''
# source ~/dotfiles-re/nvim/plugins/lightline.rc.vim
# '''

# 無駄な空白をハイライト
# [[plugins]]
# repo = 'bronson/vim-trailing-whitespace'
# 
# # インデントをハイライト
# repo = 'nathanaelkane/vim-indent-guides'
# hook_add = '''
# source ~/dotfiles-re/nvim/plugins/indent.rc.vim
# '''
# ==========================================================
# web apis
# ==========================================================
[[plugins]]
# NOTE: webapi-vim がrepo=でもcall dein#addでもインストールされない
repo = 'mattn/webapi-vim'
repo = 'mattn/gist-vim'

