# ==========================================================
# filer
# ==========================================================

# [[plugins]]
# repo = 'Shougo/unite.vim'
# on_cmd   = ['Unite', 'UniteWithBufferDir', 'UniteWithCursorWord']
# hook_add = '''"{{{
#   noremap zd :Unite dwm<CR>
#   noremap zD :Unite dein/log<CR>
#   noremap zf :Unite qfixhowm/new qfixhowm<CR>
#   noremap zF :Unite qfixhowm/new qfixhowm:nocache<CR>
#   noremap zg :Unite file_rec/async<CR>
#   noremap zG :Unite grep:.<CR>
#   "noremap <c-]> :UniteWithCursorWord -immediately tag/include<CR>
#   noremap zi :Unite tig<CR>
#   noremap zI :Unite gista<CR>
#   noremap zl :Unite outline<CR>
#   noremap zL :Unite decls<CR>
#   noremap zn :UniteWithBufferDir -buffer-name=files file file/new<CR>
#   noremap zu :Unite bundler<CR>
#   noremap zU :UniteResume<CR>
#   noremap zT :Unite tab<CR>
#   noremap zN :Unite -buffer-name=files file file/new<CR>
#   noremap zp :Unite dwm buffer_tab file_mru:long<CR>
#   noremap zP :Unite yankround<CR>
#   noremap zh :Unite ghq<CR>
#   noremap ZB :Unite rails/bundle<CR>
#   noremap ZC :Unite rails/controller<CR>
#   noremap ZD :Unite rails/db<CR>
#   noremap ZG :Unite rails/bundled_gem<CR>
#   noremap ZH :Unite rails/helper<CR>
#   noremap ZJ :Unite rails/javascript<CR>
#   noremap ZL :Unite rails/lib<CR>
#   noremap ZM :Unite rails/model<CR>
#   noremap ZO :Unite rails/command<CR>
#   noremap ZR :Unite rails/route<CR>
#   noremap ZS :Unite rails/spec<CR>
#   noremap ZT :Unite tsproject<CR>
#   noremap ZV :Unite rails/view<CR>
#   noremap Zc :Unite rails/config<CR>
#   noremap Zj :Unite rails/json_schema<CR>
#   noremap Zl :Unite rails/log<CR>
#   noremap Zm :Unite rails/mailer<CR>
#   noremap Zr :Unite rails/root<CR>
#   noremap Zs :Unite rails/stylesheet<CR>
# "}}}'''
# hook_source = 'call delphinus#init#unite#hook_source()'

[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['Shougo/denite.nvim']

# ==========================================================
# terminal
# ==========================================================

# [[plugins]]
# repo = 'kassio/neoterm'
# if = "has('nvim')"
# hook_add = '''
# source ~/.vim/nvim/plugins/neoterm.rc.vim
# '''

[[plugins]]
repo = 'Shougo/vimshell'
if = "!has('nvim')"
hook_add = '''
source ~/.vim/nvim/plugins/vimshell.rc.vim
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
if = "!has('nvim')"
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

# ==========================================================
# Yank
# ==========================================================

[[plugins]]
repo     = 'LeafCage/yankround.vim'
on_map   = ['<Plug>(yankround-']
hook_add = '''"{{{
  nmap p <Plug>(yankround-p)
  xmap p <Plug>(yankround-p)
  nmap P <Plug>(yankround-P)
  nmap gp <Plug>(yankround-gp)
  xmap gp <Plug>(yankround-gp)
  nmap gP <Plug>(yankround-gP)
  nmap <c-p> <Plug>(yankround-prev)
  nmap <expr><c-n> yankround#is_active() ? "\<Plug>(yankround-next)" : "\<Plug>DWMNew"
"}}}'''


# コメントアウト、アンコメントを楽にする
[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'scrooloose/nerdtree'

# ==========================================================
# lang
# ==========================================================

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'


[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html', 'vue']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'php', 'erb', 'scss', 'sass', 'css', 'jade', 'haml', 'pug', 'less', 'vue']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'md'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'digitaltoad/vim-jade'
on_ft = 'jade'

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = 'scss'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

# ==========================================================
# web apis
# ==========================================================
[[plugins]]
# NOTE: webapi-vim がrepo=でもcall dein#addでもインストールされない
repo = 'mattn/webapi-vim'
repo = 'mattn/gist-vim'

# ==========================================================
# Denite
# ==========================================================

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
source ~/.vim/nvim/plugins/denite.rc.vim
'''
hook_post_source = '''
call denite#custom#var('file_rec', 'command',
\ ['pt', '--follow', '--nocolor', '--nogroup', '--hidden', '-g', ''])
call denite#custom#var('grep', 'command',
\ ['pt', '--nogroup', '--nocolor', '--smart-case', '--hidden'])
call denite#custom#var('grep', 'default_opts', [])
call denite#custom#var('grep', 'recursive_opts', [])
" denite/insert モードのときは，C- で移動できるようにする
call denite#custom#map('insert', "<C-j>", '<denite:move_to_next_line>')
call denite#custom#map('insert', "<C-k>", '<denite:move_to_previous_line>')
" tabopen や vsplit のキーバインドを割り当て
call denite#custom#map('insert', "<C-t>", '<denite:do_action:tabopen>')
call denite#custom#map('insert', "<C-v>", '<denite:do_action:vsplit>')
call denite#custom#map('normal', "v", '<denite:do_action:vsplit>')
'''

