[[plugins]]
repo = 'Shougo/dein.vim'

# ==========================================================
# color
# ==========================================================

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
set background=dark
au MyAutoCmd VimEnter * nested colorscheme hybrid
au MyAutoCmd VimEnter * highlight Visual ctermbg=216
'''

# ==========================================================
# Denite (like Unite)
# ==========================================================

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
source ~/.vim/nvim/plugins/denite.rc.vim
'''
hook_post_source = '''
call denite#custom#var('file_rec', 'command',
\ ['pt', '--follow', '--nocolor', '--nogroup', '--hidden', '-g', ''])
call denite#custom#var('grep', 'command',
\ ['pt', '--nogroup', '--nocolor', '--smart-case', '--hidden'])
call denite#custom#var('grep', 'default_opts', [])
call denite#custom#var('grep', 'recursive_opts', [])
'''

# ==========================================================
# linter
# ==========================================================

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
source ~/.vim/nvim/plugins/ale.rc.vim
'''
