[[plugins]]
repo = 'Shougo/dein.vim'

# ==========================================================
# color
# ==========================================================

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
source ~/.vim/nvim/plugins/color.rc.vim
'''
