[[plugins]]
repo = 'Shougo/dein.vim'

# ==========================================================
# color
# ==========================================================

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
source ~/.vim/nvim/plugins/color.rc.vim
'''

# repo = 'w0ng/vim-hybrid'